service:
  name: patients-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  environment:
    PATIENTS_TABLE_NAME: ${self:custom.PatientsTable.name}

  iamRoleStatements:
    - ${file(iam/PatientsTableIAM.yml):PatientsTableIAM}

resources:
  Resources:
    PatientsTable: ${file(resources/PatientsTable.yml):PatientsTable}

functions:
  createPatient:
    handler: src/handlers/createPatient.handler
    events:
      - http:
          method: POST
          cors: true
          path: /patient
  
  getPatient:
    handler: src/handlers/getPatientById.handler
    events:
      - http:
          method: GET
          cors: true
          path: /patient/{id}

  getPatients:
    handler: src/handlers/getPatients.handler
    events:
      - http:
          method: GET
          cors: true
          path: /patients

  updatePatient:
    handler: src/handlers/updatePatientById.handler
    events:
      - http:
          method: PUT
          cors: true
          path: /patient/{id}
  
  deletePatient:
    handler: src/handlers/deletePatientById.handler
    events:
      - http:
          method: DELETE
          cors: true
          path: /patient/{id}


custom:
  PatientsTable:
    name: !Ref PatientsTable
    arn: !GetAtt PatientsTable.Arn
  bundle:
    linting: false