PatientsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PatientsTable-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          
          - AttributeName: name
            AttributeType: S
          
          - AttributeName: birthDate
            AttributeType: DATE

          - AttributeName: email
            AttributeType: S

          - AttributeName: address
            AttributeType: S
            
        KeySchema:
          - AttributeName: id
            KeyType: HASH